### **What is numpy?**
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### **Numpy Arrays Vs Python Sequences**
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [ ]:
import numpy as np

In [ ]:
# np.array()
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2d array
b=np.array([[1,2,4],a])
print(b)

[[1 2 4]
 [1 2 3]]


In [ ]:
#3d / tensor

c=np.array([[[1,2,4],[4,5,6],[7,8,9]],[[1,2,4],[4,5,6],[7,8,9]],[[1,2,4],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 4]
  [4 5 6]
  [7 8 9]]

 [[1 2 4]
  [4 5 6]
  [7 8 9]]

 [[1 2 4]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# i can specify data type in array
f=np.array([1,2,3],dtype=float)
print(f)

[1. 2. 3.]


In [ ]:
cl=np.array([1,3,4],dtype=complex)
print(cl)

[1.+0.j 3.+0.j 4.+0.j]


In [ ]:
# np.arange it is like range in python
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# np.reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.arange(1,28).reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
# np.ones and np.zeros used to initialize
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# np.random give value between 0 and 1
np.random.random((2,3)) # if i need 2d array then i need to use touple inside of random

array([[0.55824669, 0.71811676, 0.41422439],
       [0.16955826, 0.7646309 , 0.60674814]])

In [ ]:
# np.random.randint(lowest,highest,size)
np.random.randint(120,300,size=(2,3))

array([[277, 180, 180],
       [177, 224, 144]])

In [ ]:
np.random.random(5) # for 1d array touple is not required

array([0.43446381, 0.68434477, 0.33502798, 0.91960378, 0.24649528])

In [ ]:
np.random.uniform(120,300,5) # for float random number

array([138.33566992, 216.13054051, 245.31464713, 270.10620817,
       296.71189683])

In [ ]:
np.round(np.random.uniform(120,300,5),4) # 4 decimal point

array([217.95  , 245.7113, 219.8249, 152.8883, 186.649 ])

In [ ]:
# np.linspace it devidies the interval in equal parts and gives you array
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
# ndim -> how many dimension
# shape -> how many rows and columns
# dtype
# size -> how many item is there
# itemsize -> how much memory occupied

a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)  # 2 2d array, each row 2,column 2

In [ ]:
a2.ndim

2

In [ ]:
a3.shape

(2, 2, 2)

In [ ]:
a2.dtype

dtype('float64')

In [ ]:

print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1.itemsize

4

### Changing Data type

In [ ]:
# np.astype -> it will change the type of data into our desired one
print(a3.dtype)
a3.astype(np.int32)


int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operation

In [ ]:
# arithmetic
a=np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
a*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [ ]:
a+100

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115]])

In [ ]:
# relational
a>5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
a>=6

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
a==15

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

In [ ]:
# vector operation
b=np.arange(1,16).reshape(3,5)

a+b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [ ]:
a*b

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [ ]:
a-b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
a**b

array([[                 1,                  4,                 27,
                       256,               3125],
       [             46656,             823543,           16777216,
                 387420489,        10000000000],
       [      285311670611,      8916100448256,    302875106592253,
         11112006825558016, 437893890380859375]])

### Functions

In [ ]:

# max,min,sum,prod
a=np.arange(1,16).reshape(3,5)
aa=np.random.randint(1,100,15).reshape(3,5)
aa

array([[23, 66, 53, 22, 32],
       [50, 35, 84, 54, 50],
       [64,  3, 59, 94, 40]])

In [ ]:
np.max(aa)

np.int64(97)

In [ ]:
int(np.max(aa))

97

In [ ]:
print(np.max(aa))

97


In [ ]:
np.min(aa)

np.int64(1)

In [ ]:
int(np.sum(aa))

872

In [ ]:
np.max(aa,axis=0) # 0-> column, 1->row

array([97, 67, 90, 62, 88])

In [ ]:
np.max(aa,axis=1)

array([90, 97, 88])

In [ ]:
# mean,median,var,std
np.mean(aa)

np.float64(58.13333333333333)

In [ ]:
np.median(aa)

np.float64(62.0)

In [ ]:
np.var(aa)

np.float64(882.9155555555556)

In [ ]:
np.std(aa)

np.float64(29.71389499132612)

In [ ]:
np.sin(aa)

array([[ 0.98935825, -0.64353813,  0.89399666, -0.42818267,  0.84147098],
       [ 0.37960774, -0.96611777,  0.89399666,  0.76255845, -0.85551998],
       [-0.82181784, -0.85551998, -0.521551  , -0.7391807 ,  0.0353983 ]])

In [ ]:
np.dot(a.reshape(5,3),aa)

array([[ 463,  360,  438,  273,  399],
       [1039,  855, 1146,  642,  867],
       [1615, 1350, 1854, 1011, 1335],
       [2191, 1845, 2562, 1380, 1803],
       [2767, 2340, 3270, 1749, 2271]])

In [ ]:
np.log(aa)

array([[2.07944154, 3.61091791, 4.49980967, 3.55534806, 0.        ],
       [4.57471098, 4.11087386, 4.49980967, 3.25809654, 4.20469262],
       [4.46590812, 4.20469262, 4.02535169, 4.12713439, 4.47733681]])

In [ ]:
np.exp(aa)

array([[2.98095799e+03, 1.17191424e+16, 1.22040329e+39, 1.58601345e+15,
        2.71828183e+00],
       [1.33833472e+42, 3.10429794e+26, 1.22040329e+39, 1.95729609e+11,
        1.25236317e+29],
       [6.07603023e+37, 1.25236317e+29, 2.09165950e+24, 8.43835667e+26,
        1.65163625e+38]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[91., 96., 12.],
       [16., 85., 16.]])

In [ ]:
np.floor(np.random.random((2,3))*100)

array([[39., 88., 88.],
       [11., 66., 58.]])

In [ ]:
(np.random.random((2,3))*100)

array([[49.81204927, 15.49323548,  7.03779764],
       [11.26179614, 13.00613165, 65.65853075]])

In [ ]:
np.round(np.random.random((2,3))*100)

array([[22., 63., 69.],
       [90., 69., 12.]])

### Idexing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[2,3] # [row,column]

np.int64(11)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1]

array([[4, 5],
       [6, 7]])

In [ ]:
a3[0]

array([[0, 1],
       [2, 3]])

In [ ]:
a3[0,0]

array([0, 1])

In [ ]:
a3[0,1]

array([2, 3])

In [ ]:
a3[0,1,1]

np.int64(3)

### Slicing

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[9:4:-1]

array([9, 8, 7, 6, 5])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:] # row start:row end, column start:column end

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [ ]:
a2[0::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,0::3]

array([4, 7])

In [ ]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3=np.arange(27).reshape(3,3,3)

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel -> it convert nD array into 1D
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [ ]:
# horizontally and vertically
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Spliting

In [ ]:
a4=np.arange(16).reshape(4,4)

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(a2,2) # pass matrix and how many equal parts i nedd

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.vsplit(a4,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]