<a href="https://colab.research.google.com/github/rafayel404/Numpy/blob/main/Task_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [ ]:
a=np.empty(10)*np.nan
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

# Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a,b=map(int,input('Give numbers: ').split())
arr=np.random.random((a,b))
print(arr)
print(arr.mean())


Give numbers: 2 3
[[0.69833421 0.31590256 0.84770287]
 [0.11786806 0.82710334 0.06838427]]
0.47921588565270495


# Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [ ]:

def border(a,b):
  x=np.ones((a,b))
  x[1:-1,1:-1]=0
  return x
a=border(4,5)
print(a)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

# Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# No

# Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
np.random.randint(0,5,(5,5))

array([[2, 3, 0, 4, 2],
       [4, 0, 1, 2, 0],
       [2, 0, 3, 1, 3],
       [2, 3, 0, 0, 4],
       [0, 4, 3, 0, 4]])

In [ ]:
np.zeros((5,5))+np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [ ]:
x=np.random.randint(1,101,(10,2))
a,b=map(int,input('Give input of coordinate: ').split())
distance=[np.sqrt((a-x[:,0])**2 +(b-x[:,1])**2)]
print(x)
print(distance)


Give input of coordinate: 2 3
[[71  1]
 [24 47]
 [86  4]
 [12 60]
 [31 63]
 [ 1 12]
 [98 32]
 [81 38]
 [90 51]
 [79  1]]
[array([ 69.02897942,  49.1934955 ,  84.00595217,  57.87054518,
        66.64082833,   9.05538514, 100.28459503,  86.40601831,
       100.23971269,  77.02596965])]


In [ ]:
a = np.random.randint(1, 100, (10, 2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)

array([62, 86, 57, 82, 85, 44, 49, 92, 83, 86])

## Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

## You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

1 2 3 4 -8 -10

In [ ]:
a=input().strip().split()
np.array(a[::-1]).astype(float)

1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.])

## Count the number of elements of a numpy array.

In [ ]:
a = np.array([])
a = np.array([1, 2])
a = np.zeros((2,3))
a.size

6

Q-11: Softmax function
Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.



In [ ]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s
softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

Q-12: Vertical stack
### Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

In [ ]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)

a = np.arange(10).reshape(2, -1)
print("a=",a)
b = np.repeat(1, 10).reshape(2, -1)
print("b=",b)
print(vertical_stack(a,b))
c = np.random.random((2,5))
print("c=", c)
vertical_stack(a,b,c)


a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.63892981 0.62084241 0.90789379 0.41321047 0.39457829]
 [0.77643035 0.45263223 0.99523867 0.81502123 0.02652615]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.63892981, 0.62084241, 0.90789379, 0.41321047, 0.39457829],
       [0.77643035, 0.45263223, 0.99523867, 0.81502123, 0.02652615]])

Q-13: Dates
### Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6. The end date should be included and for simplicity, choose dates from a same year.

a= [[0 1 2 3 4]
 [5 6 7 8 9]]


### Q-14: Subtract the mean of each row from a matrix.

In [2]:
x=np.random.randint(10,26,(3,5))
x

array([[10, 15, 22, 17, 23],
       [15, 22, 24, 21, 19],
       [14, 22, 13, 10, 17]])

In [3]:
x-x.mean(axis=1, keepdims = True)

array([[-7.4, -2.4,  4.6, -0.4,  5.6],
       [-5.2,  1.8,  3.8,  0.8, -1.2],
       [-1.2,  6.8, -2.2, -5.2,  1.8]])

In [4]:
x.mean(axis=1)

array([17.4, 20.2, 15.2])

In [5]:
x.mean(axis=1,keepdims=True)

array([[17.4],
       [20.2],
       [15.2]])

### Q-15: Swap column-1 of array with column-2 in the array.

In [7]:
x=np.random.randint(10,26,(3,5))
x

array([[13, 20, 13, 18, 16],
       [18, 15, 12, 16, 18],
       [23, 15, 20, 20, 10]])

In [9]:
x[:,0]

array([13, 18, 23])

In [10]:
x[:,[0]] # this preserves dimension of column

array([[13],
       [18],
       [23]])

In [19]:
x[:,[0,2,1,3,4]]

array([[13, 13, 20, 18, 16],
       [18, 12, 15, 16, 18],
       [23, 20, 15, 20, 10]])

## Q-16: Replace odd elements in arrays with -1.

In [27]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[a%2!=0]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q-17: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

In [2]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])


In [3]:
a>b

array([ True,  True, False, False,  True])

In [7]:
a[b>a]

array([5])

In [8]:
b[a<b]

array([7])

In [11]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

## Q-18 Answer below asked questions on given array:
Fetch Every alternate column of the array
### Normalise the given array

In [13]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[6011, 4123, 1509, 6497, 6485],
       [4454,  585, 3720,   53, 5637],
       [4365, 1873, 4028,  915, 4348],
       [2105, 3348, 5896,  459, 2756],
       [9280,  486, 3187, 6007, 2468],
       [6742, 9987, 4263, 4421, 7177],
       [9334, 9910, 5985, 4637, 1610],
       [6912, 6516, 8950, 6353, 6159]])

In [14]:
arr1[:, ::2]

array([[6011, 1509, 6485],
       [4454, 3720, 5637],
       [4365, 4028, 4348],
       [2105, 5896, 2756],
       [9280, 3187, 2468],
       [6742, 4263, 7177],
       [9334, 5985, 1610],
       [6912, 8950, 6159]])

In [15]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.59975841, 0.40970405, 0.14656734, 0.6486813 , 0.64747332],
       [0.44302396, 0.05355345, 0.3691363 , 0.        , 0.56210993],
       [0.43406483, 0.18320918, 0.40014093, 0.0867727 , 0.43235353],
       [0.20656332, 0.33168915, 0.588182  , 0.04086974, 0.27209583],
       [0.92883028, 0.04358768, 0.31548218, 0.59935575, 0.24310449],
       [0.67334407, 1.        , 0.42379706, 0.43970203, 0.71713308],
       [0.93426616, 0.99224884, 0.59714113, 0.46144554, 0.15673445],
       [0.69045702, 0.65059392, 0.89561103, 0.63418563, 0.61465673]])

### Q-19: Write a function which will accept 2 arguments.
### First: A 1D numpy array arr
###Second: An integer n {Please make sure n<=len(arr)}

###utput: The output should be the nth largest item out of the array

In [16]:
def nthmax(arr, n):
    if n>len(arr):
        raise IndexError("n is way out of limit")
    arr.sort()
    return arr[-n]
nthmax(np.array([12,34,40,7,1,0]),2)

np.int64(34)

### Q-20: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [17]:
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
a = np.array([1,2,3])

In [19]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [20]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
np.hstack([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])