<a href="https://colab.research.google.com/github/rafayel404/Numpy/blob/main/Task_3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [26]:
# code
import numpy as np
ar=np.random.randint(0,100,(3,4))
ar

array([[79, 80,  2, 42],
       [30, 45, 40, 14],
       [18, 74, 63, 97]])

In [27]:
# i
np.sort(ar)

array([[ 2, 42, 79, 80],
       [14, 30, 40, 45],
       [18, 63, 74, 97]])

In [28]:
np.sort(ar,axis=0)

array([[18, 45,  2, 14],
       [30, 74, 40, 42],
       [79, 80, 63, 97]])

In [29]:
# ii
ar[ar[:,1].argsort()]

array([[30, 45, 40, 14],
       [18, 74, 63, 97],
       [79, 80,  2, 42]])

In [38]:
# iii
-np.sort(-ar,axis=1)

array([[80, 79, 42,  2],
       [45, 40, 30, 14],
       [97, 74, 63, 18]])

In [31]:
#iv
np.sort(ar,axis=None).reshape(3,4) # axis =None will flatten the matrix first and then sort every element

array([[ 2, 14, 18, 30],
       [40, 42, 45, 63],
       [74, 79, 80, 97]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

In [84]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject =np.array( [41, 87, 72, 36, 92])
# Two extra students record-
rec1 = np.array([77, 83, 98, 95, 89])
rec2 =np.array( [92, 71, 52, 61, 53])

In [85]:
marks=np.append(marks,extra_subject.reshape(5,1),axis=1)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [86]:
marks=np.append(marks,rec1.reshape(1,5),axis=0)
marks=np.append(marks,rec2.reshape(1,5),axis=0)
marks
#marks = np.concatenate((marks, np.vstack((rec1, rec2))), axis=0)
# marks = np.append(marks, np.vstack((rec1, rec2)).reshape(2, 5), axis=0)


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [87]:
marks=np.append(marks,np.sum(marks,axis=1).reshape(7,1),axis=1)
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [102]:
marks[marks[:,5].argsort()[::-1]]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

In [93]:
marks.sum(axis=1,keepdims=True)

array([[212],
       [656],
       [458],
       [468],
       [630],
       [884],
       [658]])

In [105]:
sorted(marks,key=lambda x:x[-1],reverse=True)

[array([ 77,  83,  98,  95,  89, 442]),
 array([ 92,  71,  52,  61,  53, 329]),
 array([ 63,  46,  90,  42,  87, 328]),
 array([ 67,  61,  59,  36,  92, 315]),
 array([ 82,   9,  29,  78,  36, 234]),
 array([ 39,  76,  13,  29,  72, 229]),
 array([ 13,  10,   9,  33,  41, 106])]

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [106]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [108]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

In [109]:
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [116]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
np.flip(arr)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [117]:
np.flip(arr,axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [118]:
np.flip(arr,axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [119]:
np.flip(arr,axis=[0,1])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [120]:
arr=np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]] )
X = 6

In [127]:
np.where(np.any(arr > X, axis = 1))

(array([1, 3]),)

### `Q-6:` How to convert an array of arrays into a flat 1d array?

In [128]:
 # These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [129]:
# code here
np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [145]:

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [146]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [147]:
np.max(arr)


np.int64(998)

In [148]:
arr.argmax()

np.int64(102)

In [149]:
arr=np.delete(arr,arr.argmax())

In [150]:
np.max(arr)

np.int64(997)

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [151]:
arr = np.random.random(100)
arr = np.around(arr, decimals = 3)

print("0th percentile == minimum value of the array: ", (np.percentile(arr, 0) == arr.min()))
print("100th percentile == maximum value of the array: ", (np.percentile(arr, 100) == arr.max()))
print("difference betwen 51th percenile and 50th percentile values: ", (np.percentile(arr, 51) - np.percentile(arr, 50)))

0th percentile == minimum value of the array:  True
100th percentile == maximum value of the array:  True
difference betwen 51th percenile and 50th percentile values:  0.005500000000000005
